## Numpy

Numpy is a numerical library that makes it easy to work with big arrays and matrices.

It can be used to make fast arithmetic operations with matrixes. Pandas and Numpy are usually used together, as Pandas builds on NumPy functionality to work with DataFrames.

Since Pandas is designed to work with Numpy, almost any Numpy function will work with Pandas Series and DataFrames, lets run some examples.

In [2]:
import numpy as np
import pandas as pd

In [3]:
# Create a container for a pseudo random generator
rng = np.random.RandomState()
# Create a Pandas Series from our random generator
series = pd.Series(rng.randint(0, 10, 4))
series

0    6
1    6
2    9
3    7
dtype: int32

In [4]:
# Create a Pandas Dataframe with our Numpy random generator
# Integer numbers between 0 and 10, 3 rows and 4 columns
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  0  7  2  2
1  7  7  3  4
2  4  2  2  2

We can use a Numpy function on these Pandas objects and still keep our indexes for order

In [5]:
# Calculate e^x, where x is every element of our array
np.exp(series)

0     403.428793
1     403.428793
2    8103.083928
3    1096.633158
dtype: float64

In [6]:
# Calculate sin() of every value in the DataFrame multiplied by pi and divided by 4
np.sin(df * np.pi / 4)

A         B         C             D
0  0.000000e+00 -0.707107  1.000000  1.000000e+00
1 -7.071068e-01 -0.707107  0.707107  1.224647e-16
2  1.224647e-16  1.000000  1.000000  1.000000e+00

### The Numpy Array
Numpy provides mutidimentional arrays, with high efficiency and designed for scientific calculations.

An array is similar to a list in Python and can be created from a list.

Array have useful atributes we can use. Lets start by defining three random arrays, a single dimension, a two dimension and a tri dimensional array. We will use Numpy random number generator.

In [7]:
# Import our Numpy package
import numpy as np
np.random.seed(0) #this will generate the same random arrays every time

x1 = np.random.randint(10, size=6) # one dimension
x2 = np.random.randint(10, size=(3, 4)) # two dimensions
x3 = np.random.randint(10, size=(3, 4, 5)) # tri dimensional array

All arrays have the `ndim` (number of dimensions) attribute, `shape` the size of each dimension, and `size` the total array size

In [8]:
print("x3 ndim:", x3.ndim)
print("x3 sahpe:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 sahpe: (3, 4, 5)
x3 size: 60


Other attributes for arrays are `itemsize` shows the byte size of every element in the array, and `nbytes` shows the total bytes size of the array:

In [9]:
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes", x3.nbytes, "bytes")

x3 itemsize: 4 bytes
x3 nbytes 240 bytes


#### Optional Exercise
- Create a 3x3x3 array that contains all random numbers.
- Using the previous array, square all the numbers in the array.

### Creating arrays with Numpy methods
Specially for largers arrays we can use the more efficient methods from Numpy.

In [10]:
# Create a length 10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
# Create a 3x5 float array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
# Create an array filled with a linear sequence
# Start at 0, end at 20, step size 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 1.0657892 , -0.69993739,  0.14407911],
       [ 0.3985421 ,  0.02686925,  1.05583713],
       [-0.07318342, -0.66572066, -0.04411241]])

In [17]:
# Create a 3x3 array of random integer in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[7, 2, 9],
       [2, 3, 3],
       [2, 3, 4]])

In [18]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

#### Array indexing
Similar to Python lists we can access individual elements in the array. For single dimensional arrays we can use the indexing format using `[]`

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
x1[-6]

5

We can use a similar logic for multi dimensional arrays

In [9]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [10]:
x2[0, 3] # Access row 0, column index 3

4

In [11]:
x2[2, -1] # Access row index 2, column index -1

7

We can use the same logic to change values using array indexing

In [12]:
x2[2, -1] = 2

#### Optional Exercise
- Create a new array using `arange` this array should contain a total of 4 values.
- Select only values in index 2 and index 4.
- Change the value of index 3 to 99

#### Sub arrays (slicing)
We can also use a similar syntax to Python list slicing to access only parts of the array. The syntax goes as follows:

`x[start:stop:step]`
Where default start value = 0, stop is the non inclusive stop index, and step the number of items we want to count

In [15]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [17]:
x[5:] # elements starting from the fifth index

array([5, 6, 7, 8, 9])

In [18]:
x[4:7] # elements between 4 and non inclusive 7

array([4, 5, 6])

In [19]:
x[::2] # all elements but step size 2

array([0, 2, 4, 6, 8])

In [20]:
x[1::2] # elements every two steps, starting from index 1

array([1, 3, 5, 7, 9])

We can also use negative step index. In this case the default start and stop values are inverted. This makes it a convenient way to invert an array.

In [21]:
x[::-1] # reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [22]:
x[5::-2] # inverted array starting from the fifth index at minus two step interval

array([5, 3, 1])

We can also select multi dimension sectors of an array. The syntax is similar, with every sector separated by a comma

In [23]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 2]])

In [24]:
x2[:2, :3] # rows with index 0 and 1, and columns with index 0, 1 and 2

array([[3, 5, 2],
       [7, 6, 8]])

In [25]:
x2[:3, ::2] # all rows but step size 2

array([[3, 2],
       [7, 8],
       [1, 7]])

#### Reshaping arrays
Another useful operation is reshaping, we can use the `reshape()` method. If we wanted to reshape an array by a 3 x 3 array we can use the following syntax

In [26]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

For this to work the size of the initial array must match the reshaped array.

Another common form of reshaping is converting an unidimensional array of rows or columns. We can either use `reshape` or the `nexaxis` keyword inside a slicing operation

In [27]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape(1, 3)

array([[1, 2, 3]])

In [28]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [29]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [30]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### Optional exercise
- Create a new 4x4 array.
- Select and print only the first two rows.
- Select and print only the last two columns.
- Select only the last two rows and first two columns.
- Reshape the array into a 8x2 array.

#### Array concatenation and division
We can also combine multiple arrays into one and vice versa

Concatenation can be achieved using the `np.concatenate`, `np.vstack` and `np.hstack`. `np.concatenate` takes a list of arrays as its first argument

In [31]:
x = np.array([1, 2, 3]) # create an array from a list
y = np.array([3, 2, 1]) # create a second array from a list
np.concatenate([x, y]) # array list to concatenate

array([1, 2, 3, 3, 2, 1])

In [32]:
# we can concatenate more than one array at a time
z = [99, 88, 77]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 88 77]


We can use the same logic for multidimensional arrays

In [33]:
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
np.concatenate([grid, grid]) # concatenate on the first axis. Rows

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# Concatenate on the second axis (zero indexed)
np.concatenate([grid, grid], axis=1) # concatenate on columns

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

To work with diferent sized arrays it may be easier to work with `np.vstack` vertical stack, and `np.hstack` horizontal stack

In [36]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
# stack vertically
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [37]:
# stack horizontally
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Split arrays
Finally we can split arrays using the `np.split`, `np.hplit` and `np.vsplit`. For each of these we need to pass a list of indexes that divide/split our array

In [38]:
x = [1, 2, 3, 99, 88, 77, 4, 5, 6]
x1, x2, x3 = np.split(x, [3, 5]) # split at index 3 and 5, non inclusive
print(x1, x2, x3)

[1 2 3] [99 88] [77  4  5  6]


Observe that N division/split points lead to N + 1 sub arrays. Similarly `np.hsplit` and `np.vsplit` can be used

In [39]:
grid = np.arange(16).reshape((4, 4))

In [40]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [42]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Universal Functions
Next we will look at why Numpy is important for data science and working with arrays.

The key to making computation with Numpy very fast is using vectorized operations with Numpy, they key to this is using Numpy Universal Functions. 

Here is a speed comparison between a traditional for loop and a vectorized operation in Numpy using and array that contains a million values.

In [20]:
# Traditional implementation
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [21]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.83 s ± 12.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


The code above takes several seconds to run. Lets run it now with a vectorized operation.

In [22]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [23]:
%timeit (1.0 / big_array)

2.71 ms ± 42.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


We can see that each loop and the consequent total execution time is orders of magnitude faster that the first iteration. Vectorized operations are implemented via ufuncs whose main function is to exectute repeteated operations on values in Numpy arrays.

Ufuncs (universal functions) can run between scalars and arrays, two arrays, and multi dimensional arrays.

In [27]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [28]:
# multidimensional example
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

### Numpy UFuncs
#### Array arithmetic
We have standard addition, substraction, multiplication and division

In [29]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [30]:
# unary functions for negation, exponentiation, and modulus
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


All these arithmetic operations are wrappers for Numpy functions

|Operator|	Equivalent ufunc |	Description |
|:--------:|:--------|:--------|
|+ |	np.add	| Addition (e.g., 1 + 1 = 2) |
|- |	np.subtract | Subtraction (e.g., 3 - 2 = 1)
|- |	np.negative |	Unary negation (e.g., -2)
|* |	np.multiply |	Multiplication (e.g., 2 * 3 = 6)
|/ |	np.divide |	Division (e.g., 3 / 2 = 1.5)
|// |	np.floor_divide |	Floor division (e.g., 3 // 2 = 1)
|** |	np.power |	Exponentiation (e.g., 2 ** 3 = 8)
|% |	np.mod |	Modulus/remainder (e.g., 9 % 4 = 1)

#### Trigonometric functions
We will explore trigonometric functions. Lets start by defining an array of angles.

In [31]:
theta = np.linspace(0, np.pi, 3)

In [32]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [34]:
# inverse functions
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


#### Exponents and logarithms

In [35]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [36]:
# log functions
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


#### Agregates
We can reduce array operations of any ufunc. A reduce repeatedly applies a given operation to the elements of the array until a single result remains.

Calling `reduce` on the `add` ufunc results in the sum of all elements in the array

In [37]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [38]:
x

array([1, 2, 3, 4, 5])

In [39]:
# calling reduce on multiply
# results in the product of all array elements
np.multiply.reduce(x)

120

In [40]:
# if we would like to store all the intermediate results
# we can use accumulate instead
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [41]:
np.multiply.accumulate(x)


array([  1,   2,   6,  24, 120])

### Exercises for participation credit
1. Create a new random integer array with Numpy functions. Use a random seed to guarantee the same array every time. Array must be of size (20, 5).
2. Calculate the average value of the second column of the array created in exercise 1. Calculate the sum of all elements in columns 3 and 4. You can use built in ufuncs and indexing.

We will now use a simple IoT readings dataset for this exercise. This dataset contains IoT temperature readings, where the reading was made (room) and location (reading was outside or inside a room).

3. Open the data file `IOT-temp.csv` inside the `iotdata-compressed` file, you will need some program like 7zip or Winrar to uncompress this `iotdata-compressed` folder. Open this file with Pandas and create a new Dataframe with this data. Show the first 10 rows of data. Show the last 10 rows of data. Show data points for index 300 to 350.
4. Create a new dataframe from index 1000 to 2000. Rename column `out/in` to `location`. Rename colum `room_id/id` to `room` How many of these readings were made outside? How many were inside?
5. Split your new dataframe into readings that were made inside and readings that were made outside. Create a new dataframe with only inside readings. Create a new dataframe only with outside readings. Print the mean value of the temperature for both new dataframes.
6. Save both dataframes created in exercise 5 to `csv` files.

More information about the dataset for exercises 3 and 4 in [this link](https://www.kaggle.com/datasets/atulanandjha/temperature-readings-iot-devices)